### ISSUE TITLE
Change text in Search window from "Search Posts, Maps and Briefings" 

### ISSUE THREAD

**Issue by Numnov** [OpenDevelopmentMekong/opendev-wptheme#40] opened 2015-03-31 11:31 UTC
@mishari Please change the Search text in the search section from "Search Posts, Maps and Briefings"  to either just "Search" or maybe an icon with a magnifying glass and the word "Search"

**Comment by mishari** [comment] 2015-04-07 17:13
This ok? ![open_development_mekong](https://cloud.githubusercontent.com/assets/503018/7028977/01554e18-dd84-11e4-8be3-3820145ef247.png)

**Comment by Numnov** [comment] 2015-04-09 07:21
![screen shot 2015-04-09 at 2 13 12 pm 2](https://cloud.githubusercontent.com/assets/4859982/7062024/41219192-dec3-11e4-967a-945769d95c45.png)
@mishari  and @Huyeng , thanks for the quick work on this. One small issue, the text and the magnifying glass seem to be getting cut off. Can this be fixed?

**Comment by Huyeng** [comment] 2015-04-21 07:28
@Numnov, I have tested with a few browsers that part looks fine to me. 
Could you provide further information including the browser name and its version?

**Comment by acorbi** [comment] 2015-05-03 14:51
@Numnov @Huyeng I could not reproduce it either, is this fixed? can we close it?

**Closed as completed** 2015-05-03 15:11 UTC
Labels: p1, p2, needfeedback
