### ISSUE TITLE
Display a minimum of ten news headlines on the home page

### ISSUE THREAD

**Issue by mishari** [OpenDevelopmentMekong/opendev-wptheme#17] opened 2015-03-10 15:30 UTC
<a href="https://github.com/Numnov"><img src="https://avatars.githubusercontent.com/u/4859982?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [Numnov](https://github.com/Numnov)**
_Thursday Feb 26, 2015 at 11:01 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_
_Originally opened as https://github.com/oeco/opendev-wptheme/issues/31_

---

Redesign geolocated news container to reflect this requirement and the design described in wireframe designs circulated by Internews on 12/13/14 [Note: We would prefer more than ten headlines if possible. With the removal of the briefing container beneath the geolocated news section, there should be more vertical space available.]

![skitch github1](https://cloud.githubusercontent.com/assets/4859982/6390866/b19e6b0e-bde2-11e4-99dc-d5f0ac2cf7de.png)

**Comment by mishari** [comment] 2015-03-10 15:31
<a href="https://github.com/WillieShubert"><img src="https://avatars.githubusercontent.com/u/3870349?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [WillieShubert](https://github.com/WillieShubert)**
_Friday Feb 27, 2015 at 20:37 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

Thank you for the detailed recommendations. The sidebar spacing has two important characteristics you should consider. Currently it is controlled using the "sticky posts" feature and also includes spacing for the use of featured images in its formatting. Adding more headlines into this space is difficult to impossible to implement as specified. There is an opportunity to display headlines outside of this section in the area vacated by the issue briefs. Is this an acceptable solution? We will include an improved story handing in the impending release

**Comment by mishari** [comment] 2015-03-10 15:31
<a href="https://github.com/mishari"><img src="https://avatars.githubusercontent.com/u/503018?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [mishari](https://github.com/mishari)**
_Monday Mar 02, 2015 at 12:26 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

@Numnov I think we need some answers on this.

**Comment by mishari** [comment] 2015-03-10 15:31
<a href="https://github.com/Numnov"><img src="https://avatars.githubusercontent.com/u/4859982?v=3" align="left" width="48" height="48" hspace="10"></img></a> **Comment by [Numnov](https://github.com/Numnov)**
_Tuesday Mar 03, 2015 at 08:47 GMT # Sample: Friday Sep 13, 2013 at 22:58 GMT_

---

@WillieShubert, can you provide a mock up of the intended presentation and provide more detail of its operation in relation to the geo-located news container?

**Comment by WillieShubert** [comment] 2015-03-10 23:59
Since the wireframe design was breaking the code for this feature we decided to utilize the area vacated by the issue briefs to display more stories. A wireframe is a reference design which sometimes isn't achievable when translated into code especially when other more important coding decision prove to be incompatible with the reference design

In response to this reality, we increased the number of stories displayed on the home page as specified in this issue title with the current design.

**Comment by mishari** [comment] 2015-03-17 10:13
@DBishton is this issue ok now? Can we close it?

**Comment by acorbi** [comment] 2015-05-03 15:50
@DBishton @Numnov Currently there are 4 news being shown in the box. Is this the expected behaviour? What is the state of this Issue?

**Comment by DBishton** [comment] 2015-05-05 05:54
@acorbi @mishari The current news presentation still does not meet our initial requirements. However, I propose that we close this issue and open a new one once we have a proposed approach to addressing this.

**Comment by acorbi** [comment] 2015-05-05 07:01
@DBishton yeah, as I understand, on point 2 in https://hackpad.com/Requirements-for-OD-front-page-redesign-LwIVEYRusMv there are some proposals for improving the box mentioned here. Then let's do as you suggest and close this Issue, creating a new one with the exact description on what is expected.

**Comment by acorbi** [comment] 2015-05-05 17:38
This requirement has been included in https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/78. Closing

**Closed as completed by acorbi** 2015-05-05 17:38 UTC
Labels: next release
