### ISSUE TITLE
Adapt layout for HUGE screens

### ISSUE THREAD

**Issue by acorbi** [OpenDevelopmentMekong/opendev-wptheme#436] opened 2016-01-14 22:37 UTC
Preview on @jpeizer1 screen:

![imgpsh_fullsize](https://cloud.githubusercontent.com/assets/384894/12339823/702b5258-bb17-11e5-96f8-646a994b3eb7.jpeg)

Layout should adapt to any kind of screen. For that, responsive design classes and mechanisms **already shipped** with jeo parent theme should be re-used. ( based on http://getskeleton.com/)

**Comment by kathi-aeviator** [comment] 2016-01-15 07:11
From my screen 13'' mac, not retina, firefox - it looks like this on home-site:
![bildschirmfoto 2016-01-15 um 14 10 15](https://cloud.githubusercontent.com/assets/15011163/12347575/befe1364-bb91-11e5-8c1a-ef714f35b0e0.png)

... and like this on laws site:
![bildschirmfoto 2016-01-15 um 14 03 50](https://cloud.githubusercontent.com/assets/15011163/12347556/86dce794-bb91-11e5-9f85-f1c581bae196.png)

**Comment by kathi-aeviator** [comment] 2016-01-15 07:11
@acorbi I will make short scribbles...

**Comment by kathi-aeviator** [comment] 2016-01-15 07:24
Bring boxes in one line like this:
![bildschirmfoto 2016-01-15 um 14 03 50](https://cloud.githubusercontent.com/assets/15011163/12347715/39aed00c-bb93-11e5-9446-bfad24cd4c33.png)
![bildschirmfoto 2016-01-15 um 14 10 15](https://cloud.githubusercontent.com/assets/15011163/12347714/39aec15c-bb93-11e5-8c79-452f7374d4d9.png)

For huge screens:

Please work with the flex tag in css! We will set that for all boxes - the hole side will work with set including menu!

**Comment by chris-aeviator** [comment] 2016-01-15 07:56
@acorbi

please ping me when you are online, we should coordinate on all responsive tasks as it is not clear who solves what at the moment as you are doing work of things that are assigned to me.

**Comment by jpeizer1** [comment] 2016-01-15 08:06
@acorbi @chris-aeviator  If you need any HUGE screen screenshots for particular urls to test results tell me -- I'm working on a 24 inch monitor with Firefox.

**Comment by kathi-aeviator** [comment] 2016-01-15 08:09
Thanks for that offer @jpeizer1 ! Would be good to have laws page screen view at that moment! Please put it in that issue. I'll piing you if something is missing in future!

**Comment by chris-aeviator** [comment] 2016-01-15 08:10
Perfect, we were not aware of that issue, will (back) implement skeleton classes to solve it for all other configured screen sizes.

**Comment by chris-aeviator** [comment] 2016-01-15 08:42
@acorbi 

did you do those changes to 'Opendevelopment Mekong' Header text?

Code from yesterday evening should look like the following screenshot:
![bildschirmfoto 2016-01-15 um 15 38 45](https://cloud.githubusercontent.com/assets/11522213/12348955/5bca61aa-bb9e-11e5-91bf-4be0550bd860.png)

If so please please coordinate before touching functional parts (like header text which was finished with my commit from last night)!

I was testing this on 24 screen in Berlin and did not touch positioning again afterwords (except bringing it more close together last night)

**Comment by chris-aeviator** [comment] 2016-01-15 08:45
**let's follow up on https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/346**

**Comment by jpeizer1** [comment] 2016-01-15 10:14
@kathi-aeviator Could you be clearer for me to make things easier? 
1. Please give me link to Screen you need
2. Please give me github link to place you want me to post
Thanks!
"Thanks for that offer @jpeizer1 ! Would be good to have laws page screen view at that moment! Please put it in that issue. I'll piing you if something is missing in future!"

**Comment by kathi-aeviator** [comment] 2016-01-15 12:03
1. @jpeizer1 please use this link:

https://pp.opendevelopmentmekong.net/laws to make the Screenshot of huge screen
1. You can set the screenshot directly below this post as a comment.

**Comment by jpeizer1** [comment] 2016-01-15 13:07
![alawscreen](https://cloud.githubusercontent.com/assets/16559612/12353692/02685796-bb5f-11e5-91b6-a9c82dccc45d.JPG)

here you go -- Sorry doing 18 things at once and tryinbg to get back to check this every so often

**Comment by jpeizer1** [comment] 2016-01-15 15:47
Guys I am glad to see the logo taking shape. I notice on wide screen the text separates WAAAAAAAAYYYY over to the middle and away from the logo. 

Can we please make sure the LOGO text stays LEFT-aligned so its near the logo on whatever sized screens?

![logo-wide-screen](https://cloud.githubusercontent.com/assets/16559612/12357322/326e5150-bb75-11e5-85c0-cca4074e536b.JPG)

**Comment by chris-aeviator** [comment] 2016-01-16 03:14
@jpeizer1 
Alex made some necessary technical changes to the header which caused this behavior. We gonna correct this together with all responsive layout adaption tasks this weekend.

**Comment by Huyeng** [comment] 2016-01-22 09:40
This issue raising here is already fixed on issue: https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/587
@jpeizer1, could you please confirm if the issue is fixed?

**Closed as completed** 2016-01-27 04:47 UTC
Labels: p1
