### ISSUE TITLE
Layers missing from Map Explorer

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#173] opened 2015-06-25 08:25 UTC
Map Explorer page on Open Development Mekong is currently not visualising layers on the map. They are still in the system, and visible in categories to the right, but do not display on page load, or when turned on or off.

![image](https://cloud.githubusercontent.com/assets/1206387/8350304/71331df2-1b4e-11e5-8641-0ea62b593598.png)

**Comment by Huyeng** [comment] 2015-06-25 09:43
The errors above caused by the error of the json files of cartodb. I have changed the status of those post layers that contain the error links to draft for temporary. 
@DBishton, please check those links of cartodb maps, and republish them with correct links. 

An example:  broken Json url 
The layer named GMS sea ports
Json url: https://dbishton.cartodb.com/api/v2_1/viz/ff05f57e-1404-11e5-96b9-0e5e07bb5d8a/viz.json

![screenshot_12](https://cloud.githubusercontent.com/assets/6613530/8351653/3ce34436-1b59-11e5-992e-09180f30d045.jpg)

**Comment by Huyeng** [comment] 2015-06-29 07:57
@DBishton, can we close this issue as we found that the core of the problem is not related to the code, but limited size of Cardodb.

**Closed as completed** 2015-07-01 05:15 UTC
Labels: bug, p1
