### ISSUE TITLE
Map Explorer does not display Geoserver-hosted layer

### ISSUE THREAD

**Issue by DBishton** [OpenDevelopmentMekong/opendev-wptheme#188] opened 2015-06-29 11:24 UTC
The Hansen tree cover layer hosted on ODC's Geoserver currently does not visualise on the map explorer:

![image](https://cloud.githubusercontent.com/assets/1206387/8406894/90140818-1e8b-11e5-8b75-c9a73b13bbfc.png)

https://opendevelopmentmekong.net/map-explorer/

Tile layer URL: 
http://geoserver.opendevelopmentcambodia.net:8181/geoserver/gwc/service/tms/1.0.0/Mekong_Regional_Site%3AHansen_tree_cover_2000@EPSG%3A900913@png/{z}/{x}/{y}.png

**Comment by Huyeng** [comment] 2015-06-30 09:30
The Hansen tree cover layer is showing up now. It seems the issue caused by the published date. It the changing the published date to May, the layer will be missed from the map explorer. @acorbi, please check this issue while you are working on map explorer. 

Anyways, @DBishton, the map is visualized in wrong projection, please discuss this issue with Seila. 

FYI, I'm uploading those raster layers of ODI to the new server for new geoserver, they will be ready to publish on new geoserver by tomorrow.

**Comment by acorbi** [comment] 2015-06-30 17:32
@DBishton @Huyeng The cause of the projection problem can be fixed by ticking the **Enable TMS** option in the layer settings. 

![bildschirmfoto 2015-06-30 um 19 24 22](https://cloud.githubusercontent.com/assets/384894/8437295/6f2e7f6a-1f5e-11e5-958e-16452f8849be.png)

I did it and now both **Tree cover** and **Hansen tree cover 2000** are now showing up correctly.

**HOWEVER** they seem to be the very same map... Please check it:
![bildschirmfoto 2015-06-30 um 19 31 47](https://cloud.githubusercontent.com/assets/384894/8437351/b3ed6350-1f5e-11e5-9119-8f70090486d9.png)
![bildschirmfoto 2015-06-30 um 19 31 51](https://cloud.githubusercontent.com/assets/384894/8437352/b3f15b2c-1f5e-11e5-9636-9c4cbebc3e66.png)

I will still research the relation with layers not showing up and their publication date and then close the Issue when that's fixed

**Comment by Huyeng** [comment] 2015-07-01 03:46
Great. Anyways, there is a problem with this layer. Whenever changing the publishing date to older, eg. June 15, 2015, the layer will be disappeared.

**Comment by DBishton** [comment] 2015-07-01 05:23
Thanks both. @acorbi, the TMS option makes perfect sense for the symptoms
we were seeing -- one of the dimensions was inverted. I didn't investigate
it fully as I was doing some rather hasty testing on the date issue that
Huy Eng mentions above. Both "tree cover" (test layer) and "Hansen tree
cover 2000" reference the same tile layer, so appearing exactly the same is
the expected behaviour.

I believe this issue can be closed, I will create a new one for the "layers
disappearing according to published dates" issue above.

On Wed, Jul 1, 2015 at 10:46 AM, Huyeng notifications@github.com wrote:

> Great. Anyways, there is a problem with this layer. Whenever changing the
> publishing date to older, eg. June 15, 2015, the layer will be disappeared.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/188#issuecomment-117426902
> .

## 

_Daniel Bishtonmobile:  +855968153317 | Twitter:
http://twitter.com/DanielBishton http://twitter.com/DanielBishton |
LinkedIn: http://linkd.in/Uf2YKt http://linkd.in/Uf2YKt_

**Comment by acorbi** [comment] 2015-07-01 06:53
ok, closing. Please file a new Issue describing the problem with publication dates.

**Closed as completed by acorbi** 2015-07-01 06:53 UTC
Labels: bug, p1
