### ISSUE TITLE
Logo reaction to Browser size

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#466] opened 2016-01-16 12:16 UTC
I reduced my browser in my large screen and noted the second line overlap with the logo and was concerned on laptops or older PC's this could occur dependent on display dimensions. 
![pagecrunch](https://cloud.githubusercontent.com/assets/16559612/12372356/bea04eca-bc20-11e5-828c-72161f50a0be.JPG)
lap 

You know about the issues of space between logo and text already.
![logo-crunch](https://cloud.githubusercontent.com/assets/16559612/12372359/04db3d5a-bc21-11e5-9077-5fa1e95e6c85.JPG)

**Comment by kathi-aeviator** [comment] 2016-01-16 12:58
Duplicate of this issue https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/346#issuecomment-171717066. Closing.

**Closed as completed by kathi-aeviator** 2016-01-16 12:58 UTC
