### ISSUE TITLE
Major Error- ELC Profiles Page in Production now Resolving to Failure/Error

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#852] opened 2016-05-09 18:06 UTC
Warning: include(/var/www/html/wp-content/themes/jeo/page-profiles.php): failed to open stream: No such file or directory in /var/www/html/wp-content/plugins/magic-fields-2/main.php on line 395

Warning: include(): Failed opening '/var/www/html/wp-content/themes/jeo/page-profiles.php' for inclusion (include_path='.:/usr/share/php:/usr/share/pear') in /var/www/html/wp-content/plugins/magic-fields-2/main.php on line 395

![capture](https://cloud.githubusercontent.com/assets/16559612/15122896/1e7b0042-15ef-11e6-9e95-61004c703dfc.JPG)

**Comment by acorbi** [comment] 2016-05-09 22:41
This issue was caused by an incompatibility with the magic-fields-2 plugin and the newest WP version 4.5. Fixed via https://github.com/OpenDevelopmentMekong/odm-frontend/commit/f5a9ec46d4a2db249774c0cb49f5f3f23666f30e

**Closed as completed by acorbi** 2016-05-09 22:41 UTC
Labels: bug
