### ISSUE TITLE
Internet Explorer Browser - Major Format Issue -- Two Vertical lines on each page

### ISSUE THREAD

**Issue by jpeizer1** [OpenDevelopmentMekong/opendev-wptheme#654] opened 2016-02-01 17:26 UTC
Every page on MS Windows Explorer has these two vertical lines running down the center. Its been that way for some weeks

![2lineswindowsexplore](https://cloud.githubusercontent.com/assets/16559612/12725070/e4777b80-c8de-11e5-90c8-862e6acffd54.JPG)

**Comment by chris-aeviator** [comment] 2016-02-02 03:33
Interesting Issue, thanks for reporting!

**Comment by chris-aeviator** [comment] 2016-02-02 03:34
Does it also appear when you are not selecting browser content? ( I can see in your screenshot the hightlighted text on menu and slideshow)

**Comment by chris-aeviator** [comment] 2016-02-02 03:35
Removing skull priority as this issue
- just affects internet explorer
- does not affect site usability

**Comment by jpeizer1** [comment] 2016-02-02 06:13
@chris-aeviator  This happens when you bring up https://www.opendevelopmentmekong.net/ and any other page on the site in Windows Explorer - you don't have to be doing anything -- and since Rachel brought up this issue and Windows Explorer is used by 43% of the all Internet users we feel it is a VERY serious issue and DOES affect site usability in our opinion.  So The SKULL priority will remain until it is fixed. Unless you'd like to explain to the client (Rachel) why you don't agree with her priorities.

**Comment by chris-aeviator** [comment] 2016-02-02 07:17
From a developer perspective there are far more serious problems that affect usability (this issue is more considered "cosmetic"). We have around 5% users visiting the site with IE.

I propose that we should talk together with Dan (he's off till Mon next week) as we need a better common understanding of priorisation, usage of github (currently overused as a discussion platform) and general communication flow between NY - Berlin - PP Teams.
Also the misunderstanding of testing procedures and closing issues shows that there's no common path at the moment. (now i'm discussing here too...)

![bildschirmfoto 2016-02-02 um 14 08 19](https://cloud.githubusercontent.com/assets/11522213/12742236/7bebf0fe-c9b6-11e5-95ae-4d71a0bfc50f.png)

**Comment by jpeizer1** [comment] 2016-02-02 10:29
@chris-aeviator  Your Email  is coming back OVER QUOTA (below) making any discussion with you outside of github rather difficult - Rachel at EWMI will need to contact you. I've advised her a conversation is in order regarding EWMI priorities and what is expected of Aeviator at this point and an email was sent to you both which bounced in your case. 

What you fail to appreciate and your 5% statistic fails to show is that most of EWMI's donors are from foundations and foundations overwhelmingly use Microsoft and load Microsoft explorer as a default on their employee's laptops. And that's what makes this a first line priority to fix ASAP. 

Message-id: <001401d15da1$9ee01b20$dca05160$@internautconsulting.com>
  Date: Tue, 02 Feb 2016 05:08:10 -0500
  From: Jonathan Peizer jpeizer@internautconsulting.com
  To: 'Christopher Krempel' christopher@aeviator.cc,
   "Tritt, Rachel" rtritt@ewmi.org
  Subject: RE: [opendev-wptheme] Internet Explorer Browser - Major Format Issue
   -- Two Vertical lines on each page (#654)

Your message cannot be delivered to the following recipients:

  Recipient address: christopher@aeviator.cc
  Reason: Remote SMTP server has rejected address
  Diagnostic code: smtp;553 User over quota. (#5.1.1)
  Remote system: dns;mail.ud08.udmedia.de (TCP|167.206.4.197|58148|194.117.254.48|25) (mail.ud08.udmedia.de ESMTP)

**Comment by Huyeng** [comment] 2016-02-04 03:33
I found that the issue of the two vertical lines caused by the the updating of the "Contact Form" to the right hand side. As the core of the problem is found, then I could help to fix this issue. However, I would like to fix it with this issue https://github.com/OpenDevelopmentMekong/opendev-wptheme/issues/618 that @Alex logged. Please share your comment on the issue #618 where you think that Contact form should be placed on the site. Then, I will fix them together.

**Comment by Huyeng** [comment] 2016-02-05 02:37
Fixed!

**Closed as completed by Huyeng** 2016-02-05 02:37 UTC
Labels: p1
